#
# src/sa_tool/Makefile
#
cc := gcc
cflags := -Wall -Wextra
ghost_data_dir := ../../data/ghost

#
# data/ghost/dex_to_mpk
#
dex_to_mpk:
	$(cc) $(cflags) dex_to_mpk_sa.c -o $(ghost_data_dir)/dex_to_mpk
